/// Flutter icons FoodAndDrinkIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FoodAndDrinkIcons
///      fonts:
///       - asset: fonts/FoodAndDrinkIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class FoodAndDrinkIcons {
  FoodAndDrinkIcons._();

  static const _kFontFam = 'FoodAndDrinkIcons';
  static const _kFontPkg = null;

  static const IconData food = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_cherries_and_leaf = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orange_and_slice = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bunch_of_grapes = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seeds_and_hand = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wine_bottle_and_glass_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_steak = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avocado_fruit = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottle_opener = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData champagne_with_bucket_and_ice_cubes = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish_dish = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roasted_chicken = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_bananas = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broccoli_vegetable = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sausage_and_french_fries = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circular_biscuits = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pudding_dessert = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake_with_a_cherry_on_top = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottle_opener_tool = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowl_of_soup = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish_conserve = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ramen_bowl = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corn_tortilla = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza_and_slice = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_eggplant = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yogurt_and_spoon = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData one_grape = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boling_pot = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bean_seeds = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eating_fish = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_legs_barbecue = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_carrot = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant_menu = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salami_cut = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData melting_ice_cream = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruit_salad = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hot_pepper_and_flame = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asparagus_bunch = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotel_reception_bell = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheat_leaf = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_mushroom = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowl_and_chopsticks = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beef_steak = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salad_with_lemon_drop = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ham_leg = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mellon_slice = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cream_cup_with_cherry_and_straw = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ear_of_corn = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loaf_of_bread = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish_and_lemon_slice = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roller_and_pasta = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ketchup_and_mustard_bottles = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sausage_on_fork = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oil_bottles = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shrimp = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData half_wine_glass = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_tacos = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jar_of_beer_and_foam = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant_salt_and_pepper = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shish_kebabs = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pumpkin = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pineapple = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donut = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peach = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cherries_couple = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cupcake_dessert = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wine_bottle_and_glass = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maki = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_glass_with_cover = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peach_silhouette = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lemon_slices = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mushroom = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grapes_1 = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mushroom_with_spots = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData milk_container = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_jar = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheat = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lollipop_spiral = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peas = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corn_cob = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lemonade_cocktail_glass = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_fruit = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bread_piece_with_seeds = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drink_glass_with_ice_cubes_and_a_straw = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sweet_cake_piece = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onion_half = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cupcake = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chili_pepper = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avocado_half_fruit_shape = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strawberry = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pear_half = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onion = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carrot = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cookies_couple = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake_of_celebration_with_one_candle = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drinks_bottles = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eggplant = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soda_drink_glass_with_a_straw = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData half_fruit_slice = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cream_cone = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer_jar = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_hot_jar = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lemon = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kiwi_fruit = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bananas = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grapes = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tomato = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orange = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData herbs_tea_cup = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eaten_apple_center = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheese = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
